### ISSUE TITLE
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions

### ISSUE THREAD

**Issue by hisuwh** [pulumi/actions#1014]
### What happened?

Preview pulumi build in GitHub actions on pull requests have started failing apparently for no reason.  I have tried refreshing the PULUMI_ACCESS_TOKEN

```
Error: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack select --stack org-name/stack-name --non-interactive
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
 err?: Error: Command failed with exit code 255: pulumi stack select --stack org-name/stack-name --non-interactive
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
```

### Expected Behavior

Preview build runs

### Steps to reproduce

```yaml
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: org-name/stack-name
        work-dir: ./infrastructure/packages/project
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

```

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.12.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like the same as https://github.com/pulumi/actions/issues/1010.

**Comment by hisuwh** [comment]
No because I'm using the Pulumi cloud backend not an Azure blob

**Comment by Frassle** [comment]
Yes but I suspect they might have common cause in backend information being lost somehow. I won't close this as a duplicate though, just in case it is actually unique.

**Comment by tgummerer** [comment]
@hisuwh I'm currently trying to reproduce and fix this issue, but am so far failing to reproduce this consistently (I thought I did once, but then never managed to again).  A few questions that might help me track this down:

- Does this error happen consistently for you, or is it flaky?
- Would you be willing to share the GitHub actions logs with me (can be privately via email)?
- Is the same happening with pulumi/actions@v5?

**Comment by hisuwh** [comment]
@tgummerer this is working again now.  I'm not sure what's changed - we didn't make any changes to our setup so may have been on the pulumi service side?

**Comment by tgummerer** [comment]
Ok great!  I think what happened is that `pulumi login` failed, and we silently ignored the failure. It's probably hard to figure out what exactly happened at this point, but I just merged https://github.com/pulumi/actions/pull/1062, which should at least give a better error message if this happens again.

I'm gonna close this issue out since it's no longer happening, but feel free to reopen if you'd like anything else to happen here.

**Comment by TylerHillery** [comment]
I am running into this same issue
```
Failed to login to Pulumi service: error: problem logging in: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
```

my repo is public so you can see the GitHub Action logs [here](https://github.com/TylerHillery/napkin-math-infra/actions/runs/14860315726/job/41723252457). Here is what I have for my pulumi step in the github action.

```yml
      - name: Provision Benchmark Infrastructure
        id: pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack_name }}
          work-dir: ./infra
          comment-on-summary: true
          color: always
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

I tried creating a new access token but that didn't work. 

I have another repo with the exact same github action which use to work but that's now failing too ([GitHub Actions logs](https://github.com/TylerHillery/pypacktrends/actions/runs/14860855748/job/41725076665). I wonder if there was an recent update that caused this?
