### ISSUE TITLE
[README] documented names for policy options are wrong

### ISSUE THREAD

**Issue by estyrke** [pulumi/actions#1024]
### What happened?

I was trying to add a policy pack using this Action. The README states that the options are `policy-pack` and `policy-pack-config`, but according to the code, they are actually called `policyPacks` and `policyPackConfigs`, and should be specified as semicolon-separated lists (./action.yml:70):

```yaml
  policyPacks:
    description: 'Run one or more policy packs as part of this update.'
    required: false
  policyPackConfigs:
    description: 'Path to JSON file containing the config for the policy pack of the corresponding "--policy-pack" flag.'
    required: false
```

### Example

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
