### ISSUE TITLE
Conda interoperability missing - plain bash works

### ISSUE THREAD

**Issue by geoHeil** [pulumi/actions#1040]
### What happened?

conda env not used right

### Example

I am trying to connect pulumi with github actions based on https://github.com/pulumi/actions/blob/master/examples/python-pulumi.yaml

However https://github.com/mamba-org/setup-micromamba when usng conda it looks like the conda based python is not piced up.
```
- uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          micromamba-version: '1.5.3-0'
          cache-environment: true
          cache-downloads: true
          environment-name: ci
          init-shell: >-
            bash
            zsh
          post-cleanup: 'all'

- uses: pulumi/actions@v4
        with:
          command: up
          stack-name: foo/bar/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

My envrionment.yml file looks like:

```
channels:
  - conda-forge
dependencies:
  - python >=3.11, <3.12
  - pip >= 23.3.1, <23.4
  - jinja2==3.1.2

  - pip:
      - pulumi==3.94.2
      - pulumi-aws
      - pulumi-aws-native==0.86.0
      - pulumi-databricks==1.26.0
      - pulumi-awsx==2.3.0
```

Still pulumi fails with:

```
import pulumi
      ModuleNotFoundError: No module named 'pulumi'
```

as it is not properly activating the right environment

however simple python code works fine from bash for importing pulumi

```
- name: Import pulumi in micromamba environment (bash)
  run: python -c "import pulumi"
  shell: bash -el {0}
```

Only the gitlab ci addon fails. How can this be fixed

### Output of `pulumi about`

conda env not used right

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
What does your `Pulumi.yaml` file look like?

If it has a runtime option with a `virtualenv` set like this:

```yaml
runtime:
  name: python
  options:
    virtualenv: venv
```

You'll likely need to remove the `virtualenv` option so that it doesn't try to use it's own virtual environment. Instead, change it to look like this:

```yaml
runtime: python
```

More details at https://www.pulumi.com/docs/languages-sdks/python/#virtual-environments
