### ISSUE TITLE
Issue with Azure OIDC: "Identity not found"

### ISSUE THREAD

**Issue by jooooel** [pulumi/actions#1045]
### What happened?

I'm trying to run `pulumi preview` in a GitHub Action using federated credentials with Azure OIDC. The federated credentials seem to be correctly setup. After logging in to Azure, I can access the key vault key that is used for encryption.

However, when running the Pulumi action, I get the following error:

```
Run pulumi/actions@v4
  with:
    pulumi-version: 3.96.1
    command: preview
    stack-name: tst
    cloud-url: azblob://<container>?storage_account=<storage-account>
    comment-on-pr: true
    diff: true
    work-dir: ***
    comment-on-summary: false
    github-token: ***
    expect-no-changes: false
    target-dependents: false
    refresh: false
    upsert: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    ARM_USE_OIDC: true
  
Configured range: 3.96.1
/usr/local/bin/pulumi version
v3.95.0
warning: A new version of Pulumi is available. To upgrade from version '3.95.0' to '3.96.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Pulumi 3.95.0 does not satisfy the desired version 3.96.1. Proceeding to download
Matched version: v3.96.1
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/76343dcc-b529-48ab-8c76-d3b347de74fa
Logging into azblob://<container>?storage_account=<storage-account>
pulumi preview on tst
  
  /home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77
                      : new CommandError(result);
  ^
  CommandError: code: -2
   stdout: 
   stderr: Command failed with exit code 255: pulumi preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-MrmOCd/eventlog.txt --stack tst --non-interactive
  warning: GOCOVERDIR not set, no coverage data emitted
  error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/pulumi-encryption-key-tst/***/decrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
   err?: Error: Command failed with exit code 255: pulumi preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-MrmOCd/eventlog.txt --stack tst --non-interactive
  warning: GOCOVERDIR not set, no coverage data emitted
  error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/pulumi-encryption-key-tst/***/decrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
  
      at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77:1)
      at Object.<anonymous> (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:76:1)
      at Generator.throw (<anonymous>)
      at rejected (/home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Example

This is what I have in my GitHub Action

```
  - name: "Login via Az module"
	uses: azure/login@v1
	with:
	  client-id: ${{ secrets.azure_client_id }}
	  tenant-id: ${{ secrets.azure_tenant_id }}
	  subscription-id: ${{ secrets.azure_subscription_id }}

  - name: Test Federated Credentials Login
	shell: bash
	run: |
	  az keyvault key show --vault-name *** --name pulumi-encryption-key-tst

  - name: "Pulumi preview"
	uses: pulumi/actions@v4
	with:
	  pulumi-version: 3.96.1
	  command: preview
	  stack-name: ${{ inputs.stack_name }}
	  cloud-url: ${{ inputs.stack_url }}
	  comment-on-pr: true
	  diff: true
	  work-dir: ${{ inputs.working_directory }}
	env:
	  ARM_USE_OIDC: "true"
```

### Output of `pulumi about`

Not relevant in this case? Running in GitHub Action

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
