### ISSUE TITLE
Action step comments on Pull Request even when comment-on-pr is false

### ISSUE THREAD

**Issue by JonathanCooper-humane** [pulumi/actions#1054]
### What happened?

We have a step configured with `command: refresh` and `comment-on-pr: false`.  We would expect to not get comments on the Pull Request.  The behavior we see is that if the `pulumi refresh` results in updates, it will comment on the PR.

### Example

```
 - name: Run Pulumi Refresh
      if: ${{ inputs.mode == 'preview' }}
      uses: pulumi/actions@v4
      with:
        command: refresh
        stack-name: [our-org-redacted]/${{ inputs.stack }}
        work-dir: ${{ inputs.project }}
        parallel: ${{ inputs.parallelism }}
        comment-on-pr: false
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi_token }}
```

### Output of `pulumi about`

```
CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME            VERSION
azure           5.41.0
azure-native    1.101.0
azuread         5.36.0
cloudflare      5.0.0
cockroach       0.1.0
confluentcloud  1.13.0
datadog         4.21.0
ec              0.5.1
github          5.8.0
keycloak        5.1.0
kubernetes      3.25.0
pulumiservice   0.9.0
python          unknown
random          4.12.1
tls             4.10.0
vault           5.11.0
```

### Additional context

I am aware that we could remove this step and change our preview step to have `refresh: true`.  In parallel, we are investigating whether that would be an acceptable solution.

I would still like to understand if the observed behavior is expected or if this is a bug.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
