### ISSUE TITLE
config-map not working for nested paths and multiple configs

### ISSUE THREAD

**Issue by hansarh** [pulumi/actions#1099]
### What happened?

I'm trying to use the `config-map` input to set a couple of values like this:

`config-map: '{"<stackname>:webApi:ecrImageUri": {value: "dkr.ecr.eu-west-1.amazonaws.com/device-manufacturing-web-api:${{ needs.build-container-image.outputs.image_tag }}" }, "dbMigrationDir": { value: "./db-migrator" }}'`

<stackname> is replaced with the actual repo in the workflow file, and ${{ needs.build-container-image.outputs.image_tag }} is an output from another job.

It generates the error like this 

```
 stdout: 
 stderr: Command failed with exit code 255: pulumi config set-all --stack easee/beta --plaintext device-manufacturing:webApi:ecrImageUri=831539310969.dkr.ecr.eu-west-1.amazonaws.com/device-manufacturing-web-api: --plaintext dbMigrationDir=./db-migrator --non-interactive
error: invalid configuration key: could not parse device-manufacturing:webApi:ecrImageUri as a configuration key (configuration keys should be of the form `<namespace>:<name>`)
 err?: Error: Command failed with exit code 255: pulumi config set-all --stack easee/beta --plaintext device-manufacturing:webApi:ecrImageUri=dkr.ecr.eu-west-1.amazonaws.com/device-manufacturing-web-api: --plaintext dbMigrationDir=./db-migrator --non-interactive
error: invalid configuration key: could not parse device-manufacturing:webApi:ecrImageUri as a configuration key (configuration keys should be of the form `<namespace>:<name>`)
```

### Example

```
    on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'
      workdir:
        required: true
        type: string
      role:
        required: true
        type: string
      stackname:
        required: false
        type: string
        default: 'production'


     
     - uses: pulumi/actions@v5
        with:
          command: preview
          config-map: '{"<stackname>:webApi:ecrImageUri": {value: "dkr.ecr.eu-west-1.amazonaws.com/device-manufacturing-web-api:${{ needs.build-container-image.outputs.image_tag }}" }, "dbMigrationDir": { value: "./db-migrator" }}'
          stack-name: ${{ inputs.stackname }}
          work-dir: ${{ inputs.workdir }}
          diff: true
          
```
          
          
          

### Output of `pulumi about`

/home/ubuntu/.pulumi/bin/pulumi version
v3.105.0
Pulumi version 3.105.0 is already installed on this machine. Skipping download
Logging into the Pulumi Cloud backend.

### Additional context

I'm passing the input as a string in a reusable workflow

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@hansarh, instead of `"<stackname>:webApi:ecrImageUri"` does it work without specifying the stack name, e.g. `"webApi:ecrImageUri"`?

**Comment by mikocot** [comment]
we use e.g.
`'azure-native:location': { value: "${{ inputs.region }}" }` and it seems to be working fine,
we never specify the stack name in the config map

**Comment by justinvp** [comment]
I'm going to close this as no-repro. I suspect this should work when not specifying the stack name. If you're still running into issues otherwise, please reply here or open a new issue. Thanks!

**Comment by hansarh** [comment]
The fix you suggest works for simple string variables. It is still an issue that I can not reference a path as you normally can with the `pulumi config set` command. 
```YAML
webapi:
  ecrImageUri: <URI PATH>
  ...  
```
