### ISSUE TITLE
default.run.working-directory property is not respected

### ISSUE THREAD

**Issue by runlevel5** [pulumi/actions#1258]
### What happened?

Please see example section

### Example

I have a simple pipeline:

```
jobs:
  preview:
    name: preview
    runs-on: [self-hosted, small, arm64]
    defaults:
      run:
        working-directory: ./my-project # NOTE: my pulumi project resides in this folder
    steps:
      - uses: pulumi/actions@v5
        with:
          pulumi-version: ${{ steps.versions.outputs.pulumi }}
          command: preview
          stack-name: my-org/my-stack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

When running pipeline I got the error that could not find stack, simply because `pulumi preview` does NOT respect `default.run.working-directory`

In order to fix this issue I have to explicitly declare `work-dir` in `pulumi/actions` step:

```
      - uses: pulumi/actions@v5
        with:
          work-dir: ./my-project/
```

### Output of `pulumi about`

It happens with all pulumi version from v4 to v5

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
