### ISSUE TITLE
Support for `refresh`

### ISSUE THREAD

**Issue by cobraz** [pulumi/actions#126]
Some of our workflows used the `--refresh` arg in `v1` of the Pulumi GHA. We've successfully migrated to `v2` now, but with some _hacks_. Such as how we refresh our stack.

Our workflow looks like this:

```yaml
- uses: pulumi/actions@v2
  with:
    command: refresh
    cloud-url: gs://folio-accounting-integrations-pulumi
    stack-name: accounting-integrations-${{ github.event.inputs.environment }}
    work-dir: packages/accounting-integrations
    github-token: ${{ secrets.GITHUB_TOKEN }}

- uses: pulumi/actions@v2
  with:
    command: up
    cloud-url: gs://folio-accounting-integrations-pulumi
    stack-name: accounting-integrations-${{ github.event.inputs.environment }}
    work-dir: packages/accounting-integrations
    github-token: ${{ secrets.GITHUB_TOKEN }} 
```

What we want is to pass an input, (e.g. `refresh: true`), which does the same as `--refresh` did for us. AFAIK, we either have to do `stack.refresh()` or ask to have this functionality added to Pulumi Automation SDK.

/cc @stack72 @komalali
