### ISSUE TITLE
Config-map input not working for adding value to map object as the pulumi config set command

### ISSUE THREAD

**Issue by hansarh** [pulumi/actions#1354]
### What happened?

The fix you suggested in closed issue #1099  works for simple string variables. It is still an issue that I can not reference a path as you normally can with the `pulumi config set` command to append or update a string config within a config map object. 

With the `pulumi config set` command I can insert a value to the `webapi` map object used as an example below in a stack config yaml fille. How can I do that with the `config-map` input of this action?

example object 
```YAML
config:
  MyStack:webapi:
    ecrImageUri: <URI PATH>
    cpu: 1
    memory: 512
    name: my-web-api
  ...  
```

### Example

example config object:
```YAML
config:
  MyStack:webapi:
    ecrImageUri: <URI PATH>
    cpu: 1
    memory: 512
    name: my-web-api
   ...  
```
I want to add a <URI Path> to ecrImageUri with the `config-map`  input of this action

### Output of `pulumi about`

this has happened for the all stacks in our org for many months using the ubuntu-latest runner image

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
