### ISSUE TITLE
On command failure, outputs.output is empty

### ISSUE THREAD

**Issue by smithrobs** [pulumi/actions#1360]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

On a failed command, it'd be nice for `steps.<id>.outputs.output` to contain at least the error message for usage/ingestion in subsequent steps.

Ideally, the availability of the full contents of both stdout and stderr would be excellent.

```
      - uses: pulumi/actions
        id: preview
        with:
          command: preview
          stack-name: <org>/<program>/<stack>
          message: "Generating preview"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Show Output
        if: always()
        run: |
          echo "${{ steps.preview.outputs.output }}"
```

As of v6, the "Show Output" step will contain nothing. It'd be great if it at minimum contained e.g.

```
     error: preview failed
 
 
     at Object.createCommandError (github/actions/pulumi-action/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:81:1)
     at github/actions/pulumi-action/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:204:1
     at Generator.throw (<anonymous>)
     at rejected (github/actions/pulumi-action/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
