### ISSUE TITLE
Support --exclude flags

### ISSUE THREAD

**Issue by cl0ckwork** [pulumi/actions#1362]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hello! I'd like to be able to leverage the [newly minted](https://github.com/pulumi/pulumi/pull/18828) `--exclude` flag for the commands that support it inside the github action.

My use case specifically:
We need it for refresh, or `preview --refresh` ideally we'd be able to ignore a urn on the "refresh" part of a `preview` but still get a preview for it, if possible. Though I would also be fine just splitting the steps out for explicit excludes.

Example
```yaml
      - name: Pulumi Refresh
        uses: pulumi/actions@v6
        with:
          command: refresh
          exclude: 'urn:...`
```

Elaboration
```yaml
      - name: Pulumi Refresh
        uses: pulumi/actions@v6
        with:
          command: preview
          refresh: true
          exclude: 'urn:...` # <== is exclude applied to both refresh/preview? i assume it would be.
```

### Affected area/feature

`pulumi/actions@v6` specifically `refresh` or `preview --refresh` commands.
