### ISSUE TITLE
Ability to skip commenting when there are no detected changes

### ISSUE THREAD

**Issue by abatilo** [pulumi/actions#158]
When you have a shared repository that has your code and your Pulumi, you might have a pull request that doesn't have infra changes. It would be nice of these PRs didn't have a message added to them just to say that there are no changes.

Could we add some flag to the action that will skip commenting when there are no changes detected?

**Comment by cobraz** [comment]
👋

Thanks for the suggestion!

A big thing for us with `v2` was to move the responsibility of different stacks, and functionality etc. to other Github Actions (like using [`google-github-actions/setup-gcloud`](https://github.com/google-github-actions/setup-gcloud) instead of setting up [`GOOGLE_CREDENTIALS` ourselves](https://github.com/pulumi/actions/blob/d72eddb7cc724b27594dbf263ed6456016186016/entrypoint.sh#L8)). We elected to implement pull request comments, even though that is something you'll find in the Github Marketplace. This is due to two reasons, a) ease of implementation and b) being able to fine-tune in this Action.

I really understand that you want this functionality, but I'm personally not sure it should be handled in the Github Action. I see at least three options right now:

### New output

We implement a new output which is something like `changed`. The output is `true` whenever there something changed or to be changed (preview command).

That on its own wouldn't fix your particular issue, you'll have to do some changes in your own workflow, where you take care of pull request comments in a separate step. Something like this:

_Notice that `comment-on-pr` is not set_

```yaml
...
- uses: pulumi/actions@v2
  id: pulumi
  with:
    command: preview
    work-dir: infra
    stack-name: dev
- name: 'Comment PR'
  uses: actions/github-script@0.3.0
  if: github.event_name == 'pull_request' AND steps.pulumi.outputs.changed == 'true'
  env:
    COMMENT_BODY: ${{ steps.pulumi.outputs.output }}
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}@
    script: |
      const { COMMENT_BODY } = process.env
      const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
      github.issues.createComment({ issue_number, owner, repo, body: COMMENT_BODY });
```

The benefits of adding a `changed` output the option to combine it with other Github Actions, like using [`rtCamp/action-slack-notify@v2`](https://github.com/marketplace/actions/slack-notify) to notify your team that something has changed on Slack. Or maybe [Gitter](https://github.com/marketplace/actions/gitter-notify)? [Twitter](https://github.com/marketplace/actions/twitter-action)?

**Note:** In the example above, I used `actions/github-scripts`. There are options that are even better to [Create or Update Comment](https://github.com/marketplace/actions/create-or-update-comment) (👈 that even have the ability to update comments, re #148)

### Evaluate if there are changes in your files

From what I understand, you don't want pull requests being filled with comment from Pulumi when there are no changes to the Pulumi code. In that case, why run it?

```yaml
- uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            infra:
              - 'infra/**' // <-- Point this to your pulumi folder
- uses: pulumi/actions@v2
  if: steps.changes.outputs.infra == 'true'
  with:
    command: preview
    work-dir: infra
    stack-name: dev
```

What we are doing here to evaluating if there are files changed in a directory (`infra`) in your repository. If there are no changes, we don't run `pulumi@actions` at all. Does that work for you?

### Add a new input (e.g. `skip-comment-no-change`)

Considering the fact we are handling pull request comments in our current codebase, we should consider adding the functionality to skip.

## Summary

We should evaluate if adding functionality to handle this use-case is something we want, or if this is where we draw the line and ask users to implement using other Github Actions. Would love your feedback on that; would you care if you'd have to use a separate Github Actions to [Create or Update Comment](https://github.com/marketplace/actions/create-or-update-comment)s? Or do you expect this to be an integral part of pulumi@actions?

IMHO, we probably want to add a `changed` output. It has many benefits for users, not just for this use-case, but in general. That does not exclude adding `skip-comment-no-change` as well

**Comment by abatilo** [comment]
Hi @cobraz!

Simply having an output and delegating the actual comment to something else makes perfect sense to me. It achieves every functional goal that I have.

Filtering by path is also an interesting path forward that could unblock me, but I think there's value in running the preview still as it would help raise the fact that someone might have manual edited the a resource. The changes in the PR might not be related at all but in some codebases, the infra might not change often but code does. 

There are definitely better ways to manage drift but simply running the diff every time can still be helpful.

**Comment by cobraz** [comment]
Thanks for that!

> There are definitely better ways to manage drift but simply running the diff every time can still be helpful.

@martinjt [mentioned](https://github.com/pulumi/actions/issues/126#issuecomment-802107579) a nice setup where he ran nightly workflows. Trying to recreate his setup here:

```yaml
name: Drift-check
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pulumi/actions@v2
        with:
          command: preview
          refresh: true			
          stack-name: dev
          expect-no-changes: true
```
