### ISSUE TITLE
Option to change directory?

### ISSUE THREAD

**Issue by ethomson** [pulumi/actions#18]
We were recently asked if it was possible to control the working directory when executing an action: https://twitter.com/rawkode/status/1187398751482253312

If people are checking in pulumi configuration not in their repository root then this may be a helpful configuration option?

(Apologies, I'm reasonably naive about pulumi so this request may not make sense.  😁 )

**Comment by chrsmith** [comment]
Sounds like something we can provide better support for and/or document.

**Comment by dmyers** [comment]
What about this? I use it and it works for me.

```yaml
- uses: docker://pulumi/actions
  with:
    args: preview
  env:
    PULUMI_ROOT: cloud/pulumi
```

**Comment by chrsmith** [comment]
Yup, the `PULUMI_ROOT` environment variable evidently already exists. 🙃 
https://github.com/pulumi/pulumi/blob/0bc999495e71463257bb5a53b7e872be7c2d0292/dist/actions/entrypoint.sh#L11-L14

I'll update our documentation to make this a little more discoverable. Thanks @dmyers for pointing that out!

**Comment by AshMartian** [comment]
The `PULUMI_ROOT` env variable did not work on `pulumi/actions@v4` for me 🥲 

This did the trick!
```yaml
- uses: pulumi/actions@v4
        with:
          command: preview
          color: always
          work-dir: your/folder
```
