### ISSUE TITLE
error: could not find `dotnet` on the $PATH: exec: "dotnet": executable file not found in $PATH

### ISSUE THREAD

**Issue by alaatm** [pulumi/actions#19]
I am trying to setup Pulumi with .net core but I am stuck with the above error. I have tried to use the .net setup action and added another step to test that `dotnet` command actually runs but I am still getting the error that `dotnet` command is not found.

I also tried to add `DOTNET_ROOT` env variable but to no avail!

Here is my yaml:

```yaml
name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Setup .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Test .net core
        run: dotnet --version
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Execute pulumi preview
        uses: docker://pulumi/actions
        with:
          args: preview
        env:
          PULUMI_ROOT: ./infra
          DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.0.100/x64      # This value is taken from "Test .net core" step
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          COMMENT_ON_PR: 1
```

Any help or guides would be appreciated. Thanks!
