### ISSUE TITLE
pulumi/actions@v2 expecting Pulumi v3 

### ISSUE THREAD

**Issue by satyaki1** [pulumi/actions#191]
## Expected behavior
It should not have  expecting pulumi v3

## Current behavior
Failing with Error
> Error: Major version mismatch. You are using Pulumi CLI version 3.0.0 with Automation SDK v2. Please update the SDK.

## Steps to reproduce
```shell
- name: Preview infra
        uses: pulumi/actions@v2
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK }}
          work-dir: pulumi
          comment-on-pr: true
          github-token: ${{ github.token }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

**Comment by komalali** [comment]
Hi! This error is indicating that you are using the incorrect CLI version (which probably comes from the `pulumi/action-install-pulumi-cli` action. If you are using that action to install the CLI, please pin the version to v2 as follows so you can continue using it with `pulumi/actions@v2`:
```
- name: Install pulumi
  uses: pulumi/action-install-pulumi-cli@v1.0.2
  with:
    pulumi-version: 2.25.1
```
