### ISSUE TITLE
Reorganize Pulumi actions

### ISSUE THREAD

**Issue by simenandre** [pulumi/actions#310]
At the moment, the action authenticates with Pulumi, downloads Pulumi CLI, and handles all that internally. It makes sense since we only have `pulumi/actions`, but maybe it's worth considering reorganize this.

Maybe it makes sense to have a separate action for authentication. The action exports credentials which can be used by the other GHAs. Could even set which stack?

I'm [inspired by `docker` which have split into multiple actions](https://github.com/docker?q=actions&type=source&language=&sort=); `docker/setup-qemu-actions`, `docker/setup-buildx-actions`, `docker/login-action`, `docker/build-push-actions`, `docker/bake-action`, `docker/metadata-action`. 

### Maybe something like this?

- pulumi/login
- pulumi/config (https://github.com/cobraz/pulumi-config)
- pulumi/actions
- pulumi/setup-pulumi

### Creating a common NPM package

I've talked with @stack72 about creating an NPM package that handles downloading dependencies (e.g. Pulumi CLI). Maybe something like `@pulumi-gha/setup-pulumi-cli`. IMHO, the package should only download if a Pulumi CLI doesn't exist (or are outside of the configured range). At least add the stuff we use in `pulumi/actions` and `pulumi/setup-pulumi`. Probably shouldn't use `@pulumi`, right?

### Example workflow

```yaml
name: Update tag
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: pulumi/login@v1
    with:
      cloud-url: gs://hello-there/two
      # or:
      pulumi-token: ${{ secrets.PULUMI_API_TOKEN }}
  - uses: pulumi/config@v1
    id: config
    with:
      stack-name: dev
  - uses: pulumi/config@v1
    if: ${{ steps.config.outputs.should-update === 'true' }}
    with:
      stack-name: dev
      key: unleash.tag
      value: ${{ steps.something.new-tag }}
  - uses: pulumi/actions@v3
    if: ${{ steps.config.outputs.should-update === 'true' }}
    with:
      command: preview
      stack-name: dev
```
