### ISSUE TITLE
Allow user to set secret provider when running an upsert on the stack

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/actions#338]
Currently when you run the Pulumi action with upsert:

```
 - uses: pulumi/actions@v3
      with:
        work-dir: pulumi
        upsert: true
        command: up
        stack-name: ${{ env.stack_name }}
```

you can't specify the secrets provider if it's not the default one.
