### ISSUE TITLE
Does downloadCli persist the pulumi cli across runs?

### ISSUE THREAD

**Issue by arminrosu** [pulumi/actions#356]
Hello all,

We're seeing strange behaviour in our actions, where the pulumi cli is already installed in the node images. We previously had this action installed, but no longer.

This might not actually be a bug with pulumi/actions, but I'm hoping you might be able to confirm / refute my assumption.

Details below.

The Pulumi Github App is installed in the organization. There are absolutely no other steps that would install pulumi and no other workflow which uses the action.

## Steps to reproduce

1. Use `pulumi/actions@v3` on a workflow
2. Delete that step from the workflow
3. Add a step: 

```yml
- name: Which Pulumi
  run: which pulumi || echo "no pulumi cli"
```

4. Run the workflow (manually), step outputs:

```bash
> Run which pulumi || echo "no pulumi cli"
/usr/local/bin/pulumi
```

Expected:

No cli to be installed if there's no pulumi/actions step in the workflow

Actual:

Cli is installed and has an older version.

A partial workflow.yml which should help replicate the issue is below:

```yml
name: Pulumi Update Test
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:

  pulumi-update-test:
    needs: list-apps
    name: Update changed applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # - uses: pulumi/actions@v3
      #   with:
      #     command: preview
      #     stack-name: dev
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Which Pulumi 01
        run: which pulumi || echo "no pulumi cli"

```
