### ISSUE TITLE
When Pulumi Github app is installed, cannot prevent github-actions bot from commenting as well

### ISSUE THREAD

**Issue by roblframpton** [pulumi/actions#48]
I recently added a workflow based on the [example in the documentation](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/).  I have installed the Pulumi Github app, however, I cannot find a way to prevent getting doubled up preview comments, from both the github-actions bot and the Pulumi app.  Currently my workflow looks like this:

```yaml
name: Pulumi PR preview
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: pulumi/actions@v1
        with:
          command: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IS_PR_WORKFLOW: true
          PULUMI_ROOT: infrastructure
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: 1
```

This gives me two sets of comments:

![image](https://user-images.githubusercontent.com/43182639/105202230-ab4ac680-5b39-11eb-961b-583c21743490.png)

![image](https://user-images.githubusercontent.com/43182639/105202274-b7368880-5b39-11eb-8be2-a6a80bcd9ef6.png)

I only want the latter to appear.  However, if I remove `COMMENT_ON_PR`, I get zero comments.  If I remove `GITHUB_TOKEN` I get the error `ERROR: COMMENT_ON_PR was set, but GITHUB_TOKEN is not set.`

What could I be doing wrong?
