### ISSUE TITLE
Support multiple editable PR comments: Bug for Monrepos and Matrix Stategy actions

### ISSUE THREAD

**Issue by liqnuks** [pulumi/actions#563]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

On Github Actions, if we use a matrix strategy to run a preview on PR, with `comment-on-pr = true` (and `edit-pr-comment = true`, the default value), for each check, the comment will override the same comment, resulting in at the end of the workflow, we have only one preview result: the last finished run.

### Steps to reproduce

On preview workflow:
```yaml
  preview:
    name: Pulumi - Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["app1", "app2"]
    steps:
[...]
    - uses: pulumi/actions@v3
      with:
        command: preview
        comment-on-pr: true
        work-dir: ${{ matrix.app }}
[...]
```

Expected: 

Have 1 comment on PR, for each matrix value (here, 2)

Actual: 

The same comment is updated for each matrix value
![image](https://user-images.githubusercontent.com/2562046/161811766-dda5c687-c098-4e5a-a8e9-b17693824d84.png)

Workaround:

Set `edit-pr-comment` to `false`, but the PR will be commented for each matrix value and each run of the pipeline... it can be verbose 

```yaml
  preview:
    name: Pulumi - Preview
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["app1", "app2"]
    steps:
[...]
    - uses: pulumi/actions@v3
      with:
        command: preview
        comment-on-pr: true
        edit-pr-comment: false
        work-dir: ${{ matrix.app }}
[...]
```
