### ISSUE TITLE
Can't run pulumi actions after updating the dependency

### ISSUE THREAD

**Issue by aterreno** [pulumi/actions#568]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Whenever we update our dependencies on our project for @pulumi/aws we then get an error on pulumi actions, locally the build works fine, but once online it can't find the plugin.

### Steps to reproduce

1. Update dependency i.e.     "@pulumi/aws": "^5.1.1", =>     "@pulumi/aws": "^5.1.2",
2. Let Github build
3. check logs

Expected: we have a green build that runs ok
Actual: 

```
Diagnostics:
    pulumi:providers:aws (default_5_1_2):
      error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.1.2 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.1.2`
```

**Comment by aterreno** [comment]
adding more logs


28s
Run pulumi/actions@v3
  with:
    command: up
    stack-name: internal-api-dev
    cloud-url: s3://****-pulumi
    work-dir: functions/internal-api
    message: Upgraded pulumi again; github can't find v5.1 of pulumi/aws
    comment-on-pr: false
    github-token: ***
    parallel: 2147483647
    target-dependents: false
    refresh: false
    upsert: false
    edit-pr-comment: true
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_REGION: us-east-1
    AWS_DEFAULT_OUTPUT: json
    DD_SERVICE: internal-api
    PULUMI_CONFIG_PASSPHRASE: ***
Configured range: ^3
Matched version: v3.28.0
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/d7d967db-8341-425c-b2bd-138d990898a8
pulumi up on internal-api-dev
  Updating (internal-api-dev):
  
  
  
      pulumi:pulumi:Stack internal-api-internal-api-dev running 
  
      pulumi:pulumi:Stack internal-api-internal-api-dev running read pulumi:pulumi:StackReference dev
  
      pulumi:providers:aws default_4_37_5  error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.37.5 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.37.5`
  
  @ updating...
  .
  
  
      pulumi:pulumi:Stack internal-api-internal-api-dev running read pulumi:pulumi:StackReference dev
  
      pulumi:pulumi:Stack internal-api-internal-api-dev  
      pulumi:providers:aws default_4_37_5 **failed** 1 error
   
  Diagnostics:
  
    pulumi:providers:aws (default_4_37_5):
      error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.37.5 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.37.5`
   
  Outputs:
    - internalApiUrl: "https://****.execute-api.us-east-1.amazonaws.com/dev/"
  
  Resources:
      1 unchanged
  
  Duration: 19s
  
  
  Error: code: 255
   stdout: Updating (internal-api-dev):
  
      pulumi:pulumi:Stack internal-api-internal-api-dev running 
      pulumi:pulumi:Stack internal-api-internal-api-dev running read pulumi:pulumi:StackReference dev
      pulumi:providers:aws default_4_37_5  error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.37.5 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.37.5`
  @ updating....
      pulumi:pulumi:Stack internal-api-internal-api-dev running read pulumi:pulumi:StackReference dev
      pulumi:pulumi:Stack internal-api-internal-api-dev  
      pulumi:providers:aws default_4_37_5 **failed** 1 error
   
  Diagnostics:
    pulumi:providers:aws (default_4_37_5):
      error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.37.5 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.37.5`
   
  Outputs:
    - internalApiUrl: "https://*****.execute-api.us-east-1.amazonaws.com/dev/"
  
  Resources:
      1 unchanged
  
  Duration: 19s
  
  
   stderr: [resource plugin aws-5.1.2] installing
  
  Downloading plugin: 0 B / 100.02 MiB    0.00%
  Downloading plugin: 6.01 MiB / 100.02 MiB    6.01% 3s
  Downloading plugin: 11.86 MiB / 100.02 MiB   11.86% 2s
  Downloading plugin: 17.55 MiB / 100.02 MiB   17.55% 2s
  Downloading plugin: 23.54 MiB / 100.02 MiB   23.54% 2s
  Downloading plugin: 28.95 MiB / 100.02 MiB   28.94% 2s
  Downloading plugin: 34.77 MiB / 100.02 MiB   34.76% 2s
  Downloading plugin: 39.78 MiB / 100.02 MiB   39.77% 2s
  Downloading plugin: 46.22 MiB / 100.02 MiB   46.21% 1s
  Downloading plugin: 51.44 MiB / 100.02 MiB   51.43% 1s
  Downloading plugin: 60.59 MiB / 100.02 MiB   60.58% 1s
  Downloading plugin: 77.08 MiB / 100.02 MiB   77.07%
  Downloading plugin: 90.84 MiB / 100.02 MiB   90.82%
  Downloading plugin: 98.83 MiB / 100.02 MiB   98.82%
  Downloading plugin: 100.02 MiB / 100.02 MiB  100.00% 2s
  
   err?:

**Comment by Frassle** [comment]
This looks like https://github.com/pulumi/pulumi/issues/5619.

I'm guessing things work if you manually install the aws plugin before running?

**Comment by aterreno** [comment]
Feel free to close this as it's effectively a dupe of https://github.com/pulumi/pulumi/issues/5619

**Comment by aterreno** [comment]
Just in case someone ends up here I've also commented this on the linked issue:

```
One more on this, I think I've found a fix that works and it's decent enough (also adds just about 8 secs of overhead) 

```yaml
      - name: Install packages
        run: yarn install
      - name: Install pulumi aws plugin
        run: pulumi plugin install resource aws v5.9.2 # matching package.json "@pulumi/aws"        
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ inputs.stack }}
          cloud-url: s3://.... 
          message: ${{ github.event.head_commit.message }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
```

I think the docs of this action should change, because without forcing a reinstall of the plugin you are effectively blocked from upgrading the provider.
