### ISSUE TITLE
AWS_PROFILE not working, commands failing

### ISSUE THREAD

**Issue by bombillazo** [pulumi/actions#601]
### What happened?

In pulumi-aws v5+, it is now required to set the AWS_ACCESS_KEY and AWS_SECRET_KEY when specifying the provider profile.

[GH Issue](https://github.com/pulumi/pulumi-aws/issues/1897#issuecomment-1106899341)
[Terraform Provider Update](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication)

Given this, I am attempting to pass `AWS_PROFILE` as an env parameter to the actions [as recommended here](https://github.com/pulumi/pulumi-aws/issues/1928#issuecomment-1116410815). However, this does not work and there is no way to relate the credentials to the was profile so Pulumi does not fail the command.

### Steps to reproduce

1. Have an aws profile setup in your was provider.

```yml
- name: Pulumi preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: myStack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_PROFILE: ${{ env.AWS_PROFILE }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
```

### Expected Behavior

Actions can use the credentials set in the CI/CD process to the profile passed in the actions automatically. Command runs successfully.

### Actual Behavior

Commands fail with the following error:

`error configuring Terraform AWS Provider: failed to get shared config profile, my-profile`

### Versions used

@pulumi/aws     5.4.0
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.32.1
@pulumi/random  4.6.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
