### ISSUE TITLE
Is there a way I can disable pulumi comment

### ISSUE THREAD

**Issue by MishaKav** [pulumi/actions#713]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I run the `pulumi/actions@v3` with the following parameters (also tried to run `comment-on-pr: false/edit-pr-comment: true`

```yaml
- name: Pulumi UP
  uses: pulumi/actions@v3
  with:
    work-dir: pulumi/cd
    comment-on-pr: true
    edit-pr-comment: true
    command: up
    stack-name: devus
```
Is there a way I can disable the first comment that comes from `pulumi`?
![image](https://user-images.githubusercontent.com/289035/186265093-e87ed72a-a3f5-4201-894d-d345f4f24cb2.png)
