### ISSUE TITLE
v1 GitHub Action deprecation notice - 24th Feb 2021

### ISSUE THREAD

**Issue by stack72** [pulumi/actions#73]
On Friday 26th February 2021, v2 of the Pulumi GitHub Action will be published. This is a new GitHub Action based on TypeScript rather than being a dockerfile based GitHub Action. 

### What Impact Will This Have On Me?

The functionality that existed in the old dockerfile based action has changed. The action originally handled things such as:

* gcloud auth activate-service-account
* gcloud --quiet auth configure-docker
* yarn workspace install / yarn install
* npm ci / npm install
* pip3 install / pipenv install

These actions are no longer handled by the new version of the action. The new action will only handle:

* pulumi login
* pulumi <command> [flags]

### What is the benefit?

The new Action works much better with the vast ecosystem of other Actions. Rather than an opinionated container with specific tool versions and specified workflows, the new Action focuses solely on Pulumi and lets you set up and customize the rest.

The original container would allow a GitHub Action usage as follows:

```yaml
name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pulumi/actions@v1
        with:
          command: up
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

This allowed no customization of the workspace. The new action allows this:

```yaml
name: Pulumi
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - uses: pulumi/actions@v2
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

The new action is also much faster! The original action had an overhead of approximately 3 minutes to download the docker container and that was before any Pulumi commands. The new NodeJS-based action is much quicker, taking approximately 25 seconds to run before any Pulumi commands.

### When Will The Old Container Be Removed?

We are committed to building the old docker based action for the next 6 months. That means we plan to remove the action from our image creation cycle August 31st 2021. During this 6 month period, we will be making sure that critical security patches of the dockerfile are applied and deloyed but we will not be accepting PRs to add new functionality to the docker based action. 

### Feedback

We are always interested in understanding the usage of the new action and how you feel it would need to change. Please open any issues / feature requests that you believe would be of use!
