### ISSUE TITLE
Pulumi Github app does not show the diff

### ISSUE THREAD

**Issue by Olsenius** [pulumi/actions#733]
### What happened?

The Pulumi github app does not show the diff like the github action does with `comment-on-pr: true` and `diff: true`. 

Is there a way to fix this?

### Steps to reproduce

```yaml
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: scaleaq/prod
          refresh: true
          diff: true
          pulumi-version: v3.19.0
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

### Expected Behavior

Pulumi github app should include the diff as the github actions comment does. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/198483/192970276-67e4042f-118f-4bd7-a5ad-55f0a09674a8.png)

### Additional context

`pulumi-version: v3.19.0` is set to get the diff ref: https://github.com/pulumi/actions/issues/731#issuecomment-1261181584 

Original question on [Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1664435055916279)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @Olsenius I just want to confirm that this bug isn't related to https://github.com/pulumi/actions/issues/731 ?
Do you have the same issue when you pin the action to v3.19.0?

**Comment by Olsenius** [comment]
Ill test on Monday when im back from my vacation.

ons. 5. okt. 2022, 19:33 skrev Robbie McKinstry ***@***.***>:

**Comment by Olsenius** [comment]
I have now tried both 

```
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: scaleaq/prod
          refresh: true
          diff: true
          pulumi-version: v3.19.0
```

and 

```
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: scaleaq/prod
          refresh: true
          diff: true
          # pulumi-version: v3.19.0
```

And neither runs shows the diff in the output.

![image](https://user-images.githubusercontent.com/198483/194830043-e3368978-b8f3-4190-b7f8-f96044aad553.png)
