### ISSUE TITLE
Python project with NO stack config file throws JSON decoding error

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/actions#778]
### What happened?

Running a github actions pipeline for a Python project that does not have (nor need) a stack config file (e.g. Pulumi.dev.yaml) fails with:

```
Diagnostics:
    pulumi:pulumi:Stack (python-github-actions-test-dev):
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/pulumi/3.46.1/x64/pulumi-language-python-exec", line 81, in <module>
          config_env = pulumi.runtime.get_config_env()
        File "/home/runner/work/githubactions-test/githubactions-test/venv/lib/python3.8/site-packages/pulumi/runtime/config.py", line 59, in get_config_env
          return json.loads(env_config)
        File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
          return _default_decoder.decode(s)
        File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
          raise JSONDecodeError("Expecting value", s, err.value) from None
      json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  
      error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

The code runs fine from my workstation 

### Steps to reproduce

- Create the world's smallest Pulumi project: 

(I.e. it has nothing in the `__main__.py` file.
```
"""A Python Pulumi program"""
```

- Set up a github actions file like this:

```
name: Pulumi Preview Test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev # When using an individual account, only use stack-name.  
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

- `pulumi stack init dev`
- run `pulumi preview` on your workstation and see that it succeeds fine without a `Pulumi.dev.yaml` file
- Run the github actions without `Pulumi.dev.yaml`
- See error given above.
- Run github actions with `Pulumi.dev.yaml` and see that it's fine.

### Expected Behavior

Github actions should not fail if no stack config file provided.

### Actual Behavior

github actions fails while command line does not

### Output of `pulumi about`

**Pulumi about from github runner:**
```
CLI          
Version      3.44.2
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.8.10
'

Dependencies:
NAME           VERSION
pip            22.3.1
pkg_resources  0.0.0
pulumi         3.46.1
setuptools     65.5.1
wheel          0.38.4
```

**Pulumi about from my workstation:**
```
CLI          
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in python: executable='/Users/mitch/.pyenv/shims/python3' version='3.9.6
'

Current Stack: dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::python-github-actions-test::pulumi:pulumi:Stack::python-github-actions-test-dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/MitchGerdisch
User           MitchGerdisch
Organizations  MitchGerdisch, team-ce, upstarts, demo, mitch-onelogin-test

Dependencies:
NAME        VERSION
pip         22.3.1
pulumi      3.46.1
setuptools  65.5.1
wheel       0.38.4
```

### Additional context

I also installed pulumi version 3.44.2 on my workstation and it still behaved correctly.
So it appears to be github actions specific.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
My current bet is that `selectStack` requires the stack config file to exist. Going to confirm with a repro.

**Comment by RobbieMcKinstry** [comment]
Aha! I was able to repro using the Automation API! The problem appears to be in AutoAPI: when you call `up`, it attempts to parse the stack's file and errors when it doesn't find it.

**Comment by MitchellGerdisch** [comment]
Just want to note that it fails in github actions with command set to `preview` as well.

**Comment by knocte** [comment]
FYI we're also affected by this (F#, not Python).

**Comment by knocte** [comment]
> FYI we're also affected by this (F#, not Python).

FYI our workaround is downgrading generic `pulumi/actions@v3` to specific `pulumi/actions@v3.19.1`.

**Comment by RobbieMcKinstry** [comment]
Thank you @knocte that's helpful information for diagnosing the issue! :)

**Comment by jalmeroth** [comment]
I ran into this as well and worked around it like this:

ˋˋˋYAML
      - uses: pulumi/actions@v3
        env:
          PULUMI_CONFIG: '{}'
ˋˋˋ

The string must be JSON loadable.

**Comment by cobraz** [comment]
I'm seeing this issue in a project I'm having too.

Thank you all for the help on this! @RobbieMcKinstry are we sure it's connected to Automation API then? I'm not sure about the inner workings that cause this specifically; would it make sense to hotfix it in our action in any way?

**Comment by justinvp** [comment]
I can't repro this using a local automation API with the latest `@pulumi/pulumi` or in a workflow using `pulumi/actions@v4`. Looks like it was fixed by https://github.com/pulumi/pulumi/pull/11943.

**Comment by Frassle** [comment]
It looks like we fixed this for node but comments on community slack (and the original report on this issue) is that this is a problem for Python as well.

**Comment by Zaubeerer** [comment]
Yes! 

I want to set up staging infrastructure using pulumi with GitHub Actions.
Therefore, I created an action via the yml as attached.
However, I get the following error. The required environment variables are created as secrets.

```
stderr: Command failed with exit code 255: pulumi preview --parallel 2147483647 --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-MohqPJ/eventlog.txt --stack beer/staging --non-interactive
```

github_action.yml

<details>

```yml
name: E2E

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  setup-ec2:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Installing dependencies
      run: pip install -r infrastructure/requirements.txt
    - name: pulumi preview
      uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: beer/staging
        work-dir: infrastructure/worker
        comment-on-pr: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

```

</details>


Applying the [workaround mentioned above](https://github.com/pulumi/actions/issues/778#issuecomment-1327006031) worked for me.
