### ISSUE TITLE
Integrate with GitHub Deployment API

### ISSUE THREAD

**Issue by jhamman** [pulumi/actions#796]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great if Pulumi's actions could integrate with [GitHub's deployment API](https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28). This would be very helpful in tracking the status of deployments within the GitHub UI. I could imagine a 1:1 mapping of Pulumi stacks to GitHub [Environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment), similar to how Vercel does this.

![image](https://user-images.githubusercontent.com/2443309/206325428-d3eb26b3-dc81-43d4-9ced-1c754f12866c.png)

### Affected area/feature

I think this could be scoped to only impact the action itself. Ideally, Pulumi could seed the GitHub deployment API when the action starts and finalize its status when complete.

**Comment by RobbieMcKinstry** [comment]
Good thinking @jhamman! Thanks for referencing Vercel as an example workflow. I'll noodle on this a bit and ask a few colleagues for their thoughts. It's possible another team has implemented something similar.

**Comment by RobbieMcKinstry** [comment]
I checked in with the Service team. They suggested we could use Pulumi's SaaS to manage the callbacks. I'm inclined to go a simpler route, and suggest we re-implement the deployments logic.

It looks like [this is doable](https://octokit.github.io/rest.js/v19#repos-create-deployment) with Octokit. I need to read the documentation, but I expect the workflow is something like:

* [ ] Create a Deployment, providing the Environment and the SHA/commit/branch identifier.
* [ ] After the run is complete, submit an `Update Deployment Status` request based on the status code.

This feels like it would accomplish the goal without ballooning the scope of this issue too much.

**Comment by jhamman** [comment]
Thanks @RobbieMcKinstry, fwiw, I've got a bit of a workaround working now:

```yaml

    steps:

      - name: Turnstyle
        ...
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev
      ... # steps to setup deployment env
      - name: Apply infrastructure update
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.pulumi.outputs.domain }}
          state: "success"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.pulumi.outputs.domain }}
          state: "failure"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
```

This _works_ but it would be much nicer if the Pulumi action (or SaaS) did this for me :)
