### ISSUE TITLE
comment-on-pr-number ignored unless event type is `pull_request`

### ISSUE THREAD

**Issue by bennettp123** [pulumi/actions#802]
### What happened?

I'm trying to use `comment-on-pr-number` within a push event to ensure PR comments work as expected. However, it doesn't attempt to comment on the PR

### Steps to reproduce

1. Add the workflow below
2. Merge a PR into the `main` branch

```yaml
# main.yml

on:
  push:
    - main

jobs:
  pulumi:
    steps:
    - uses: jwalton/gh-find-current-pr@v1
        id: pr
        with:
          state: all
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ inputs.stack-name }}
          comment-on-pr-number: ${{ steps.pr.outputs.pr }}
          edit-pr-comment: false
```

### Expected Behavior

* `pulumi up` action is triggered
* output is posted to the merged PR as a comment

### Actual Behavior

* `pulumi up` action is triggered
* status is not added to the merged PR

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
