### ISSUE TITLE
Encoding problems when using the github pull request comment feature

### ISSUE THREAD

**Issue by doddi321** [pulumi/actions#814]
### What happened?

When I use the pull request comment feature the encoding of the output is all weird: 

```
�[38;5;13m�[1mPreviewing update (VirtualTourGuide/development)�[0m

�[38;5;13m�[1mView Live: �[4m�[38;5;12mhttps://app.pulumi.com/VirtualTourGuide/CloudInfrastructure/development/previews/c6fc313a-7822-4904-aabd-501fe1a1e727�[0m

�[0mrunning 'dotnet build -nologo .'�[0m
�[0m  Determining projects to restore...
�[0m
�[0m  Restored /home/runner/work/VirtualTourGuideApi/VirtualTourGuideApi/DevOps/CloudInfrastructure/CloudInfrastructure.csproj (in 1.45 sec).
�[0m
�[0m  CloudInfrastructure -> /home/runner/work/VirtualTourGuideApi/VirtualTourGuideApi/DevOps/CloudInfrastructure/bin/Debug/net7.0/CloudInfrastructure.dll
�[0m
�[0m
Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:07.01
�[0m
�[0m'dotnet build -nologo .' completed successfully�[0m
�[0m  pulumi:pulumi:Stack: (same)
�[0m    [urn=urn:pulumi:development::CloudInfrastructure::pulumi:pulumi:Stack::CloudInfrastructure-development]
�[0m�[0m    �[38;5;3m~ gcp:cloudrunv2/service:Service: (update)
�[0m        [id=projects/virtualtourguide-369322/locations/europe-north1/services/virtualtourguide-api]
�[0m�[0m        [urn=urn:pulumi:development::CloudInfrastructure::gcp:cloudrunv2/service:Service::virtualtourguide-service]
�[0m�[0m        [provider=urn:pulumi:development::CloudInfrastructure::pulumi:providers:gcp::default_6_45_0::cb9d9545-9724-416a-b9b2-e0b32a8c899e]
�[0m�[38;5;3m      ~ template: �[0m�[38;5;3m{
�[0m�[38;5;3m          ~ containers: �[0m�[38;5;3m[
�[0m�[38;5;3m              ~ [0]: �[0m�[38;5;3m{
�[0m�[38;5;3m                      ~ image: �[0m�[38;5;3m"�[0m�[0meurope-north1-docker.pkg.dev/virtualtourguide-369322/container-images/test@�[0m�[38;5;1mlatest�[0m�[38;5;3m"�[0m�[38;5;3m => �[0m�[38;5;3m"�[0m�[0meurope-north1-docker.pkg.dev/virtualtourguide-369322/container-images/test@�[0m�[38;5;2msha256:9d904553138f321ae35f3be4b46446947bdbf7da121f8564e1bd7d1071ade65e�[0m�[38;5;3m"
�[0m�[38;5;3m                    }
�[0m�[38;5;3m            ]
�[0m�[38;5;3m        }
�[0m�[0m�[38;5;13m�[1mResources:�[0m
�[38;5;3m~ 1 to update�[0m
35 unchanged
```

### Steps to reproduce

Here is the workflow file:

```yaml
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs: 
  test: 
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'

    runs-on: ubuntu-latest
    steps: 
      - uses: 'actions/checkout@v3'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_EMAIL }}

      - uses: pulumi/actions@v3
        with:
          command: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          stack-name: VirtualTourGuide/development
          work-dir: ./DevOps/CloudInfrastructure
          upsert: true
          comment-on-pr: true
          color: always
          diff: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

### Expected Behavior

Expected not to have the � character appear

### Actual Behavior

The � character appears

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
