### ISSUE TITLE
Request for release of `remove` stack functionality

### ISSUE THREAD

**Issue by djbb7** [pulumi/actions#825]
### What happened?

The `remove` functionality to destroy a stack is not working for me. It seems that it has not yet been released. The PR #759 was merged on the 17th of November, but the latest release [v3.20.0](https://github.com/pulumi/actions/releases) dates to the November 10th.

Is there an estimated time for the next release?

### Steps to reproduce

Create a workflow that uses the `remove` input in combination with `command: destroy` input.

```yaml
name: pulumi-cleanup
on:  
  workflow_dispatch:
    inputs:
      org_name:
        required: true
        type: string
      stack_name:
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Destroy resources and stack
        uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: ${{inputs.org_name}}/${{inputs.stack_name}}
          work-dir: infra
          remove: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

### Expected Behavior

The stack resources are deleted, and then the stack is removed.

### Actual Behavior

> Warning: Unexpected input(s) 'remove', valid inputs are ['command', 'stack-name', 'work-dir', 'comment-on-pr', 'comment-on-pr-number', 'github-token', 'cloud-url', 'secrets-provider', 'parallel', 'message', 'config-map', 'expect-no-changes', 'diff', 'replace', 'target', 'target-dependents', 'policyPacks', 'policyPackConfigs', 'refresh', 'upsert', 'edit-pr-comment', 'pulumi-version', 'color']

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
