### ISSUE TITLE
Enable suppressing outputs

### ISSUE THREAD

**Issue by samox73** [pulumi/actions#849]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, when `comment-on-pr` is set to `true` and the stack outputs objects, the output is also shown in the comment on the PR. This pollutes the diff view which resources will be changed. It would be helpful to have a flag (similar to the pulumi CLI) to disable printing the outputs.

**Comment by dixler** [comment]
Hi. This sounds like a nice addition. Do you think you could put an example of a normal comment and what the desired comment would look like just for clarity?

This isn't on our roadmap, but we would be willing to merge a feature like this if were implemented.

**Comment by alexiskat** [comment]
This is my config in Github action
```
      - name: Preview changes to Infra  🚀
        uses: pulumi/actions@v4
        id: pulumi_review
        with:
          command: preview
          stack-name: ${{ env.PULUMY_DEV_XXXXX }}
          work-dir: ${{ env.PULUMY_DEV_XXXXX }}
          color: always
          diff: true
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_INFRA_XXXXX }}
```
At the moment with this I am getting hit with the issue reported #859 . The output in the PR comment looks like this:
<img width="787" alt="Screenshot 2023-02-23 at 09 16 00" src="https://user-images.githubusercontent.com/46929771/220866041-98f164d7-2a73-4b11-931f-aad3c825040a.png">

This debugging information goes on for pages. I think its to verbose. At the end it has this:
<img width="878" alt="Screenshot 2023-02-23 at 09 19 58" src="https://user-images.githubusercontent.com/46929771/220866592-47ceef79-53c3-4063-a7ac-22f21b24c927.png">

I could expect that the output in the PR comment would be the same as when you run the `preview` command in the `terminal`, to just give you the information about the stack changes and not to include all the python install output as above
