### ISSUE TITLE
Outputs Cant be Accessed

### ISSUE THREAD

**Issue by darena-patrick** [pulumi/actions#850]
### What happened?

I am using GitHub actions to do a configuration drift check on a cron schedule. I am creating an issue in GitHub when drift is detected. When creating the issue, the results of the diff can't be accessed.

### Steps to reproduce

```
      - uses: pulumi/actions@v4
        id: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          stack-name: ${{ env.stack }}
          command: preview
          refresh: true
          expect-no-changes: true
          diff: true
```
When I attempt to access the stack output as below, it comes back blank:
```
${{ steps.pulumi.outputs.output }}
```

### Expected Behavior

I would expect same output that would be there if `comment-on-pr` were set to `true`. Since my action is running on cron rather than pr, I’m unable to use that command.

I can see here that `outputs.output` should be valid:
https://github.com/pulumi/actions/blob/f7bafdc41134b9184439a15d2c3a94c44f42d84b/action.yml#L96-L98

### Actual Behavior

Outputs are blank

### Output of `pulumi about`

Dependencies:
NAME                VERSION
Pulumi              3.45.0
Pulumi.AzureAD      5.30.0
Pulumi.AzureNative  1.83.0
Pulumi.Random       4.8.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Huh, interesting... I'll have to take a closer look at this.

**Comment by olafurnielsen** [comment]
Came across this issue while also working on creating a workflow for drift detection. This issue is caused by the setting of expect-no-changes: true in the configuration, which results in the pulumi-cli tool to exit with a status code of 255, causing the step to fail immediately. Attempts to use continue-on-error: true produced empty step output.

I'm guessing this is because this action only [sets contents of stdout](https://github.com/pulumi/actions/blob/master/src/main.ts#L77) as the action output but ignores stderr outputs.

A workaround I came up with is to install the Pulumi CLI using the `pulumi/setup-pulumi` action, run `pulumi preview [desiredarguments]`, set an output status with the command's exit code, set an output with the stdout contents, use a condition in the next step `if: steps.pulumi-drift.outputs.status != 0`, and then create the desired outcome, such as create an issue.

This is how I did this:
```YAML
      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0

      - name: Detect drift
        id: pulumi-drift
        working-directory: ${{ matrix.workdir }}
        #continue-on-error: true
        shell: bash {0}
        env:
          PYTHONPATH: ${{ matrix.workdir }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          out=$(pulumi preview --refresh --diff --expect-no-changes --stack "${{ matrix.stack }}")
          printf 'status=%s\noutput<<EOF\n%s\nEOF' $? "$out" >> $GITHUB_OUTPUT

      - name: Create issue
        if: steps.pulumi-drift.outputs.status != 0
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKDIR: ${{ matrix.workdir }}
          STACK: ${{ matrix.stack }}
          OUTPUT: ${{ steps.pulumi-drift.outputs.output }}
        with:
          filename: .github/daily-drift.md
          update_existing: true
          search_existing: open
```

The daily-drift.md template I use looks like this:
````markdown
---
title: Drift detected for {{ env.WORKDIR }}:{{ env.STACK }}
assignees: olafurnielsen
---

## Drift detected for {{ env.WORKDIR }}:{{ env.STACK }}

Details:
- **Date: {{ date | date('YYYY-MM-DD') }}**
- **Project: {{ env.WORKDIR }}**
- **Stack: {{ env.STACK }}**

Following is the output of `pulumi preview --refresh --diff --expect-no-changes -s {{ env.STACK }}`:

```
{{ env.OUTPUT }}
```
````
