### ISSUE TITLE
kubectl authentication coming in GKE v1.26

### ISSUE THREAD

**Issue by Moon1706** [pulumi/actions#853]
### What happened?

Hi folks! I'm wondering why nobody talked about [this issues](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke).

### Steps to reproduce

```yaml
jobs:
  pulumi_compare_stacks_develop:
    runs-on: self-hosted
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: "Auth to GCP exist stack"
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ env.WLI_PROVIDER_DEV }}
          service_account: ${{ env.SERVICE_ACCOUNT_DEV }}
      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: "Set up NodeJs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install NPM requirements"
        run: npm install
      - name: "Compare new and exist stack"
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ env.STACK_NAME_DEV }}
          cloud-url: ${{ env.CLOUD_URL_DEV }}
          diff: true
          color: always
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_DEV }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: true
          # also checked USE_GKE_GCLOUD_AUTH_PLUGIN: True
```

### Expected Behavior

Avoid warning

### Actual Behavior

W0124 13:51:39.445265     533 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.

### Output of `pulumi about`

Difficult to say, but:
pulumi: `3.52.1`,
kubernetes cluster: `1.22`

### Additional context

I suppose we should append additional `USE_GKE_GCLOUD_AUTH_PLUGIN` env [here](https://github.com/pulumi/actions/blob/master/src/libs/envs.ts) and put this value in [`envVars`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/x/automation/#Workspace-envVars).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
