### ISSUE TITLE
Support reusing credentials from azure/login action

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/actions#881]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In https://github.com/Azure/login#github-action-for-azure-login I followed their guidance on how to do a login for the azure CLI. According to their recommendation, I configured the federated credentials (using Pulumi!)

```typescript
new azuread.ApplicationFederatedIdentityCredential("github-integration-credentials", {
  applicationObjectId: appRegistration.objectId,
  audiences: ["api://AzureADTokenExchange"],
  displayName: `GithubIntegrationEnvironment-${stackName}`,
  issuer: "https://token.actions.githubusercontent.com",
  subject: `repo:{redacted}:environment:${stackName}`,
  description: `Github integration for pulumi stack ${stackName}`
}, { dependsOn: [appRegistration], parent: appRegistration })
```

Then I setup my github action for PRs to login. I was hoping pulumi action would actually pick the credentials from it.

```yaml
- name: Configure Azure Credentials
  uses: azure/login@v1
  with:
    client-id: ${{ secrets.APP_CLIENT_ID }}
    tenant-id: ${{ secrets.APP_TENANT_ID }}
    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
- name: Preview Infra Changes
  uses: pulumi/actions@v4
  with:
    command: preview
    stack-name: {redacted}
    comment-on-pr: true
  env:
    PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

Then I got an error message in the result:

```
azure-native:resources:ResourceGroup (resource-group):
error: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
     
To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
auth method - instructions for which can be found here: https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication
      
Alternatively you can authenticate using the Azure CLI by using a User Account.
```

It could be good to actually support reusing those credentials from azure login once federated credentials are safer to use and don't expire like client credentials.

### Affected area/feature

- Pulumi CLI
- Pulumi Github Action
