### ISSUE TITLE
No python dependencies install is needed for the action

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/actions#891]
### What happened?

If you follow the workflow example in https://github.com/pulumi/actions/blob/master/examples/python-pulumi.yaml you will see that the packages are installed twice. Once from the `pip install` and again from the Pulumi action.

In addition, packages from the pulumi action execution are not being cached if I add `cache: pip` into the `setup-python action`

### Expected Behavior

It was expected to have the install dependencies removed and the packages to be cached.

### Steps to reproduce

Some steps in a Github workflow:
```
steps:
  - name: Turnstyle
    uses: softprops/turnstyle@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: Checkout code
    uses: actions/checkout@v3
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      cache: pip
  - name: Deploy Infra Changes
    uses: pulumi/actions@v4
    with:
      command: up
      stack-name: <redacted>
      upsert: true
      work-dir: ./infra
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.APP_TENANT_ID }}
```

### Output of `pulumi about`

CLI          
Version      3.58.0
Go Version   go1.20.1
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/<redacted>
User           <redacted>
Organizations  <redacted>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by chrisjohnson00** [comment]
`cache: pip` works for global pip installs, this action seems to be installing via a virtual environment, so you'd want to use `cache: pipenv` to save off the packages installed by the action.

**Comment by chrisjohnson00** [comment]
Signing off for the day, but I think this can just be solved by fixing the example (I'll try to remember to PR this change).  This works and caches the PIP packages:

```
  pulumi:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      - name: Installing PyPi dependencies for Pulumi
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Pulumi
        uses: pulumi/actions@v4
      - name: Pulumi Up
        run: |
          pulumi preview --stack org/project/stack
```

I don't see requirements being installed a second time.
Also a nice thing with this approach... I don't want `requirements.txt` to contain both my app packages AND Pulumi; this method allows me to use `pulumi_requirements.txt` for Pulumi and keep `requirements.txt` for app only packages.
