### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/actions#926]
### What happened?

Action output

```
Run pulumi/actions@v4
Configured range: ^3
/usr/local/bin/pulumi version
v3.63.0
warning: A new version of Pulumi is available. To upgrade from version '3.63.0' to '3.64.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
Pulumi version 3.63.0 is already installed on this machine. Skipping download
Logging into the Pulumi Service backend.
pulumi preview on foo/bar/preview
Warning: Not able to edit comment, defaulting to creating a new comment.
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/pulumi/actions/v4/webpack:/pulumi-github-action/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Expected a comment on my PR

### Steps to reproduce

```
- name: Preview infrastructure 🚀
        if: github.event_name == 'pull_request'
        uses: pulumi/actions@v4
        with:
          command: preview
          comment-on-pr: true
          stack-name: foo/bar/preview
          work-dir: py/projects/infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

### Output of `pulumi about`

```
CLI          
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME       VERSION
aws        5.37.0
command    0.7.2
docker     4.2.0
github     5.8.0
nuage      0.1.1
python     unknown
random     4.13.0
snowflake  0.20.0

Host     
OS       darwin
Version  13.3.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi Louis, 
`HttpError: Resource not accessible by integration` reads to me like an issue with the permissions on the Pulumi app integration. The warning `Warning: Not able to edit comment, defaulting to creating a new comment.` sounds like it's also hinting to a permissions error.

**Comment by blytheaw** [comment]
I am also getting this issue. I am not using Pulumi Cloud, but an S3 backend. I assumed the purposed of this flag was in the event you aren't Pulumi Cloud + the GitHub App to get comments. Does this flag still require Pulumi Cloud access to add the comment even if cloud-url is not a Pulumi Cloud login?

**Comment by RobbieMcKinstry** [comment]
AFAIK you can use this feature without enabling the app, you don't need to be logged into the Pulumi Cloud. If you're not using the Pulumi app, then you may be encountering this error because `${{ github.token}}` [might not have sufficient permissions to post the comment](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

Are you editing the permissions of `GITHUB_TOKEN` at all?

**Comment by blytheaw** [comment]
@RobbieMcKinstry I am not doing anything explicitly to modify github token permissions. It's not clear to me from that link if the default permissions allow putting comments or not.

**Comment by blytheaw** [comment]
@RobbieMcKinstry Never mind, I'm blind. I was modifying the token permissions. As I am using GitHub OIDC for AWS access I had to modify the token permissions, so adding `pull-requests: write` to the token permissions got me sorted out:

```
permissions:
  id-token: write
  contents: read
  pull-requests: write
```

Thanks!
