### ISSUE TITLE
OIDC instead of Access Token

### ISSUE THREAD

**Issue by gsuess** [pulumi/actions#927]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Assuming that the pulumi cloud will support OIDC authentication (currently it doesn't seem like it), this action could support OIDC quite seamlessly. The `PULUMI_ACCESS_TOKEN` env would be omitted and the org would be parsed from the stack-name.

```yml
- name: Preview changes
   uses: pulumi/actions@v4
   with:
       command: up
       stack-name: myorg/dev
```

### Affected area/feature

Pulumi Service Authentication
