### ISSUE TITLE
Matrix job not respecting stack name.

### ISSUE THREAD

**Issue by maurerbot** [pulumi/actions#93]
Matrix job does not respect the stack name, it runs on what seems like the first matrix job to hit the pulumi/actions step.

## Expected behavior
The matrix step should respect the stack name

## Current behavior
The matrix step is running the same stack every time

## Steps to reproduce
Below is the job definition:
```
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      stacks: ${{ steps.filter.outputs.changes }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2.9.0
        id: filter
        with:
          filters: |
            gcp: 'deploy/gcp/**'
            github: 'deploy/github/**'
            gke: 'deploy/gke/**'
            kubelt: 'deploy/kubelt/**'

  preview:
    needs: changes
    if: >
      github.event_name == 'pull_request'
      && needs.changes.outputs.stacks != '[]'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    strategy:
      matrix:
        stack: ${{ fromJson(needs.changes.outputs.stacks) }}
    steps:
      - uses: actions/checkout@master
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.KUBELT_STUDIO_SA_KEY }}
          project_id: ${{ env.KUBELT_STUDIO_PROJECT_KEY }}
          export_default_credentials: true
      - uses: pulumi/actions@v1
        with:
          command: preview
          stack-name: proofzero/${{ matrix.stack }}
        env:
          PULUMI_ROOT: deploy/${{ matrix.stack}}
          IS_PR_WORKFLOW: true
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

![image](https://user-images.githubusercontent.com/695698/109390826-d9ae8500-78e1-11eb-9368-0bb7bf67486e.png)

**Comment by stack72** [comment]
Hi @maurerbot 

Yesterday we actually released a new v2 of the action - we've actually deprecated v1 as it's a docker based action

There's a migration guide in the README and I'm very confident that the new action will alleviate this type of error

Paul

**Comment by maurerbot** [comment]
I did the migration but we have a new issue now...

```  preview:
    needs: changes
    if: >
      github.event_name == 'pull_request'
      && needs.changes.outputs.stacks != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ${{ fromJson(needs.changes.outputs.stacks) }}
    steps:
      - uses: actions/checkout@master
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.KUBELT_STUDIO_SA_KEY }}
          project_id: ${{ secrets.KUBELT_STUDIO_PROJECT_KEY }}
          export_default_credentials: true
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - uses: pulumi/actions@v2
        with:
          github-token: ${{ secrets.BOT_TOKEN}}
          work-dir: deploy/${{ matrix.stack }}
          command: preview
          stack-name: proofzero/${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

```
   stdout: Previewing update (proofzero/gcp)
  
  View Live: https://app.pulumi.com/proofzero/***/gcp/previews/1bd7c385-7007-437a-b7d4-c1e097057e65
  
      pulumi:pulumi:Stack ***-gcp  Creating virtual environment...
      pulumi:pulumi:Stack ***-gcp  Finished creating virtual environment
      pulumi:pulumi:Stack ***-gcp  Updating pip, setuptools, and wheel in virtual environment...
      pulumi:pulumi:Stack ***-gcp  Collecting pip
      pulumi:pulumi:Stack ***-gcp    Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
      pulumi:pulumi:Stack ***-gcp  Collecting setuptools
      pulumi:pulumi:Stack ***-gcp    Downloading https://files.pythonhosted.org/packages/4e/ca/0456249eead852a957d306feb0cce454b823cbc3bea7821971febfa45f99/setuptools-53.1.0-py3-none-any.whl (784kB)
      pulumi:pulumi:Stack ***-gcp  Collecting wheel
      pulumi:pulumi:Stack ***-gcp    Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
      pulumi:pulumi:Stack ***-gcp  Installing collected packages: pip, setuptools, wheel
      pulumi:pulumi:Stack ***-gcp    Found existing installation: pip 9.0.1
      pulumi:pulumi:Stack ***-gcp      Uninstalling pip-9.0.1:
      pulumi:pulumi:Stack ***-gcp        Successfully uninstalled pip-9.0.1
      pulumi:pulumi:Stack ***-gcp    Found existing installation: setuptools 39.0.1
      pulumi:pulumi:Stack ***-gcp      Uninstalling setuptools-39.0.1:
      pulumi:pulumi:Stack ***-gcp        Successfully uninstalled setuptools-39.0.1
      pulumi:pulumi:Stack ***-gcp  Successfully installed pip-21.0.1 setuptools-53.1.0 wheel-0.36.2
      pulumi:pulumi:Stack ***-gcp  Finished updating
      pulumi:pulumi:Stack ***-gcp  Installing dependencies in virtual environment...
      pulumi:pulumi:Stack ***-gcp  Collecting pulumi<3.0.0,>=2.0.0
      pulumi:pulumi:Stack ***-gcp    Downloading pulumi-2.21.2-py2.py3-none-any.whl (138 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting pulumi-gcp<5.0.0,>=4.0.0
      pulumi:pulumi:Stack ***-gcp    Downloading pulumi_gcp-4.12.0.tar.gz (1.3 MB)
      pulumi:pulumi:Stack ***-gcp  Collecting protobuf>=3.6.0
      pulumi:pulumi:Stack ***-gcp    Downloading protobuf-3.15.3-cp36-cp36m-manylinux1_x86_64.whl (1.0 MB)
      pulumi:pulumi:Stack ***-gcp  Collecting grpcio!=1.30.0,>=1.9.1
      pulumi:pulumi:Stack ***-gcp    Downloading grpcio-1.36.0-cp36-cp36m-manylinux2014_x86_64.whl (4.1 MB)
      pulumi:pulumi:Stack ***-gcp  Collecting dill>=0.3.0
      pulumi:pulumi:Stack ***-gcp    Downloading dill-0.3.3-py2.py3-none-any.whl (81 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting six>=1.12.0
      pulumi:pulumi:Stack ***-gcp    Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting pyyaml>=5.3.1
      pulumi:pulumi:Stack ***-gcp    Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting semver>=2.8.1
      pulumi:pulumi:Stack ***-gcp    Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting parver>=0.2.1
      pulumi:pulumi:Stack ***-gcp    Downloading parver-0.3.1-py2.py3-none-any.whl (14 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting arpeggio~=1.7
      pulumi:pulumi:Stack ***-gcp    Downloading Arpeggio-1.10.1-py2.py3-none-any.whl (54 kB)
      pulumi:pulumi:Stack ***-gcp  Collecting attrs>=19.2
      pulumi:pulumi:Stack ***-gcp    Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
      pulumi:pulumi:Stack ***-gcp  Building wheels for collected packages: pulumi-gcp
      pulumi:pulumi:Stack ***-gcp    Building wheel for pulumi-gcp (setup.py): started
      pulumi:pulumi:Stack ***-gcp    Building wheel for pulumi-gcp (setup.py): finished with status 'done'
      pulumi:pulumi:Stack ***-gcp    Created wheel for pulumi-gcp: filename=pulumi_gcp-4.12.0-py3-none-any.whl size=2240335 sha256=720720a571223cb5ec559c451bc4a08569eca8b80232255cd64317cc79b7a925
      pulumi:pulumi:Stack ***-gcp    Stored in directory: /home/runner/.cache/pip/wheels/72/f2/a9/d179ae7b56f9c332ea932deddc202bd3ac1ddd066f14923fd9
      pulumi:pulumi:Stack ***-gcp  Successfully built pulumi-gcp
      pulumi:pulumi:Stack ***-gcp  Installing collected packages: six, semver, pyyaml, protobuf, grpcio, dill, attrs, arpeggio, pulumi, parver, pulumi-gcp
      pulumi:pulumi:Stack ***-gcp  Successfully installed arpeggio-1.10.1 attrs-20.3.0 dill-0.3.3 grpcio-1.36.0 parver-0.3.1 protobuf-3.15.3 pulumi-2.21.2 pulumi-gcp-4.12.0 pyyaml-5.4.1 semver-2.13.0 six-1.15.0
      pulumi:pulumi:Stack ***-gcp  Finished installing dependencies
      pulumi:pulumi:Stack ***-gcp  
   
  
   stderr: error: failed to discover plugin requirements: The 'virtualenv' option in Pulumi.yaml is set to "venv", but "/home/runner/work/***/***/deploy/gcp/venv" doesn't exist; run the following commands to create the virtual environment and install dependencies into it:
  
      1. python3 -m venv /home/runner/work/***/***/deploy/gcp/venv
      2. /home/runner/work/***/***/deploy/gcp/venv/bin/python -m pip install --upgrade pip setuptools wheel
      3. /home/runner/work/***/***/deploy/gcp/venv/bin/python -m pip install -r requirements.txt
  
  
  For more information see: https://www.pulumi.com/docs/intro/languages/python/#virtual-environments
  
   err?: 
```

**Comment by stack72** [comment]
So in your Pulumi.yaml there's a venv section specified as part of the runtime setup so Pulumi is expecting that to be available

The action expects the environment to be fully configured - so you'd need to do something like this:

```bash		
$ python3 -m venv venv		
$ source venv/bin/activate		
$ pip3 install -r requirements.txt
```

**Comment by stack72** [comment]
I can check to see if there's something missing in our docs that talks about this or is missing regarding what we expect

**Comment by maurerbot** [comment]
@stack72 thanks for the quick replies. 

The venv setting is a generated config that I figured was needed -- tested that commands still work locally. Howver, without the `options: virtualenv: venv` we get this following error.

```
   stdout: Previewing update (proofzero/gke)
  
  View Live: https://app.pulumi.com/proofzero/***/gke/previews/e5b9b453-65d0-4146-a831-c872dc1a7e3d
  
  
      pulumi:pulumi:Stack ***-gke  Traceback (most recent call last):
      pulumi:pulumi:Stack ***-gke    File "/home/runner/.pulumi/bin/pulumi-language-python-exec", line 14, in <module>
      pulumi:pulumi:Stack ***-gke      import pulumi
      pulumi:pulumi:Stack ***-gke  ModuleNotFoundError: No module named 'pulumi'
      pulumi:pulumi:Stack ***-gke  It looks like the Pulumi SDK has not been installed. Have you run pip install?
      pulumi:pulumi:Stack ***-gke  If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
      pulumi:pulumi:Stack ***-gke  error: an unhandled error occurred: Program exited with non-zero exit code: 1
      pulumi:pulumi:Stack ***-gke  1 error; 6 messages
   
  Diagnostics:
    pulumi:pulumi:Stack (***-gke):
      Traceback (most recent call last):
        File "/home/runner/.pulumi/bin/pulumi-language-python-exec", line 14, in <module>
          import pulumi
      ModuleNotFoundError: No module named 'pulumi'
      It looks like the Pulumi SDK has not been installed. Have you run pip install?
      If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
   
      error: an unhandled error occurred: Program exited with non-zero exit code: 1
   
  
  
   stderr: 
   err?: 
```

**Comment by maurerbot** [comment]
I think I'm missing

```
- name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
```
